### ISSUE TITLE
fx:include - Not able to set any property

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#11]
Originally reported by: **Alexander Casall (Bitbucket: [acasall](https://bitbucket.org/acasall), GitHub: Unknown)**

----------------------------------------

We heavily use fx:include. There is a one big problem with it. If you have an included element in the Scene Builder, you are not able to set any property. (screenshot)

Workaround:
- add properties like Anchor Constraints by written FXML

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/11

**Comment by garzy** [comment]
Please fix the point **3.Resources cannot be set due to an error in FXMLLoader.**

With this solution.

https://community.oracle.com/thread/2595439

I've tested this fix on my framework and works!!  Only you have to wrap the loaded resourceBunle into an a ResourceBundleWrapper instance and operate with the wapper instance!.

I think that it's a big JavaFX FXML bug, but this fix it's better than nothing (which is unacceptable to me)

**Comment by abhinayagarwal** [comment]
@garzy Would it be possible for you to create a PR with the fix?

**Comment by garzy** [comment]
Ok,  I will try to solve it in the weekend but I do not promise anything,
since I have solved it in the code of my project, not in SceneBuilder.

**Comment by garzy** [comment]
**Hi, I'm founded a working solution!**

First, I think that the problem has been fixed some time ago because FXMLLoader instead of  throw "NullPointerException" (the error that I have), Scenebuilder it's throwing "MissingResourceException" because FXML doesn't find the way to find de .properties.

This it's very simillar issue that I'm having when when I tried to import my custom components lib but my lib are using anothers thidparty libs.

Bot problems can be fixed attaching the libs to the SceneBuilder classpath.

To do this, I only know by setting the "app.classpath" property of the "SceneBuilder.cfg".

for example:

```
app.classpath=./thirdpartylibs/jfxtras-labs-8.0-r6.jar;./thirdpartylibs/myproject.jar;

Secenebuilder:
 - dist.jar
 - LICENSE
 - Scenebuilder.cfg
 - thirdpartylibs
         - jfxtras-labs-8.0-r6.jar
         - myproject.jar
```

I had to create an a "temporal jar" of my project that has the .properties files inside. With this way Scenebuilder loads my fxml well.

Example tag:

`<fx:include fx:id="myEditor" source="../myeditor/myEditor.fxml" resources="com.garzy.views.myeditor.myeditor"/>
`

inside jar I have 

```
com/garzy/views/myeditor/myeditor_en.properties
com/garzy/views/myeditor/myeditor_es.properties
```

### It's works!

> **So I think that the problem it's that Scenebuilder would be include an a graphical mecanish to allow add jars or folder to operate.  Or at least search in relative locations of fxml that is being loaded, as it is done with the images and the comtroller validation. ¿why no with the resources?**
