### ISSUE TITLE
Japanese characters in the main menu are garbled in Windows Installer version

### ISSUE THREAD

**Issue by aoetk** [gluonhq/scenebuilder#194]
### Description

Japanese characters in the main menu are garbled in Windows Installer version.
This problem only occurs in version 10.0.0 and Windows Installer version.
This problem doesn't occur in Executable Jar version and Windows environment.
I guess the message resource file was broken during the process of building the installer for Windows.

![sb10issuejapanese](https://user-images.githubusercontent.com/735573/44309251-fe673f00-a3fe-11e8-8e0d-279d11969df3.png)

### Product Version

JavaFX Scene Builder 10.0.0 Windows Installer
### Operating System

Windows 10

### Language Environment

Japanese

**Comment by torutk** [comment]
I can't find native packaging script(batch file) in integration-9 branch, but in .ci directory in master branch.
In case of native packaging for integration-9(JDK 9+), would I use the files for native packaging from
master branch?

**Comment by torutk** [comment]
This issue occurs on Scene Builder 11.0.0 Windows Installer.

**Comment by torutk** [comment]
This issue seemed to fix .ci\build.bat by adding "-Dfile.encoding=UTF-8"
before:
`call gradlew check shadowJar -PVERSION=%APPVEYOR_REPO_TAG_NAME%`
after:
`call gradlew check shadowJar -PVERSION=%APPVEYOR_REPO_TAG_NAME% -Dfile.encoding=UTF-8`

**Comment by torutk** [comment]
Scene Builder 15.0.1 Windows Installer has this issue.

This issue is caused by gradle build on the OS that default encoding is not UTF-8 like Windows OS.

app/build.gradle
`filter(EscapeUnicode)`
This filter reads the file as default encoding, then generates escape unicode file.

So, build on Windows OS(English edition), gradle treats the resource property file as CP1252 encoding and generates escape unicode. 

This breaks the Japanese resource property file 'app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp_ja.properties'
