### ISSUE TITLE
Font letter it's broken on macOS

### ISSUE THREAD

**Issue by brunogptavares** [gluonhq/scenebuilder#347]
As can be seen in the screenshots, the font letters appear broken, especially the letters 'p' and 'o'.

### Expected Behavior

The font letter should be readable.

### Current Behavior

The font letter appear to be broken.

### Steps to Reproduce

Just open SceneBuilder from launchpad on Mac.

### Your Environment

macOS BigSur 11.2.3
Mac mini (2018)
Monitor SyncMaster 20'' (1680x1050)

### Screenshots

![Captura de ecrã 2021-04-02, às 23 38 41](https://user-images.githubusercontent.com/2218801/113459432-6252a080-940d-11eb-90a9-b8c7fe2a536e.png)
![Captura de ecrã 2021-04-02, às 23 57 35](https://user-images.githubusercontent.com/2218801/113460200-c2e2dd00-940f-11eb-891b-ee6a0bf67165.png)

**Comment by Oliver-Loeffler** [comment]
I ran some tests on macOS Big Sur 11.3.1 with Java-11 and Java-16 installed and can only party reproduce the issue.
The test was conducted on MacBook Pro (Retina, 15', Mid 2015). 
The character distortion on the Gluon Scene Builder welcome page exists but the bad font rendering in the main window is not reproducible.

<img width="274" alt="Bildschirmfoto 2021-08-04 um 19 09 08" src="https://user-images.githubusercontent.com/22102800/128232256-f0a11c20-b36f-4401-9425-b90ae01e42bf.png">

<img width="254" alt="Bildschirmfoto 2021-08-04 um 19 40 19" src="https://user-images.githubusercontent.com/22102800/128232287-b7860521-5129-4f94-8f43-a70d5b1f0f4f.png">

@brunogptavares 
There is a test build which contains all changes in master since March (the DMG is not signed).
I would appreciate if you could try out the test build and report your findings.

[SceneBuilder_16.0.0-SNAPSHOT-issue-362.dmg](https://github.com/Oliver-Loeffler/scenebuilder/raw/issue-362-deb-test/testbuilds/SceneBuilder_16.0.0-SNAPSHOT-issue-362.dmg)

The difference of this build to master is a different definition of the JVM setting `java.library.path`. I have found, that in some cases wrong libraries in the default `java.library.path` can cause graphics corruption. Hence, this is a test if this issue might be also related to that.

The broken rendering of the string "New Project" is interesting, as it does not occur in other strings. This is something to investigate.

**Comment by brunogptavares** [comment]
@Oliver-Loeffler I just download the DMG, but I got an error saying that SceneBuilder is damage, when I try to run it.

**Comment by mrlimbic** [comment]
I had problems with broken font & weird text coloration with my own app in recent versions of Mac OS.

It happens on my mac mini with HDMI connected monitor since Big Sur and is probably a bug in javafx.

Starting my app with "-Dfile.encoding=UTF-8 -Dprism.lcdtext=false" improves the text.

Not a perfect solution as text looks less smooth but it does fix the coloration & missing pieces. So is more readable.

I just updated from javafx 8 to javafx 17 and was disappointed to find this is stilll an issue on some of my macs.

**Comment by brunogptavares** [comment]
@mrlimbic It really must be a javafx bug, looks like it's resolved with javafx 18, at least the font looks better in my app.

**Comment by mrlimbic** [comment]
I'll check if 18 solves it. The problem with this bug is it depends a lot on the monitor hardware you are using. It doesn't apply to all displays. 

I know it still happens with latest 17 but not on every machine. Anyway the workaround is easy. Just turn off LCD text rendering.

**Comment by brunogptavares** [comment]
This problem does not occur in Scene Builder 18.0.0.

**Comment by SlaweksHub** [comment]
I noticed the same problem with version 21.0.0. My environment is similar to above, though my monitor is 32". The screenshot would look exactly the same.

The fix by mrlimbic worked. 

You have to right click the app in finder, choose 'Show package contents' go to Contents / App and edit the file SceneBuilder.cfg. Under [JavaOptions] you change the line beginning with 'java-options' to:
java-options=-Djpackage.app-version=21.0.0 -Dprism.lcdtext=false

MacOS won't allow you to save the file there. So you need to make a duplicate, name it SceneBuilder.cfg, save it somewhere else, and drag the file into Contents / App  in Finder. Click 'Replace'.

It looks, well, better. You can work like this.

I'm writing this because I tried Scene Builder many years ago and I thought it was broken on Mac OS X, the edges of the fonts looked somehow blurry, so I didn't even consider ever developing with JavaFX when it looks so bad.

You could make the java-options above the default on mac and allow the user to switch it in view menu, even if it means restarting the application.

This is really a sensitive topic. If your app looks bad, the first time people try it, it won't catch on like ever. I took a second look now, only because Scala has support for JavaFX.
