### ISSUE TITLE
Provide Apple Silicon pre-build version of SceneBuilder

### ISSUE THREAD

**Issue by wanghongfei** [gluonhq/scenebuilder#367]
Provide  Apple Silicon pre-build version of SceneBuilder.

### Expected Behavior
M1 native build of SceneBuilder should run much faster than current intel build.

### Context
I'm using macbook pro with the M1 ARM chip. I downloaded the latest version of ScendBuilder and found that it runs unbearably slow. Then I managed to build the source code by using Zulu's Apple Silicon JDK16 and Gluon's Apple Silicon JavaFX SDK and it perfectly works. I suggest that we should provide this M1 native build out of the box instead of letting people build it mannually.

**Comment by pengzexuan2001** [comment]
M1上确实太卡了，简易可以考虑出一个M1版本😂

**Comment by pengzexuan2001** [comment]
M1上确实太卡了，简易可以考虑出一个M1版本😂

**Comment by jperedadnr** [comment]
@wanghongfei Scene Builder 18.0.0 has just been released, and you can find an installer for M1: https://github.com/gluonhq/scenebuilder/releases/tag/18.0.0

**Comment by Siedlerchr** [comment]
@jperedadnr  Could you please elaborate how you did this? We are also using jpackage to build our app for mac. Is there a trick to build this on an intel machine or do I need an M1 mac for this?

**Comment by jperedadnr** [comment]
I've just built it on an M1

You can do it with the proper JDK, JavaFX, [jmods](https://download2.gluonhq.com/openjfx/18/openjfx-18_osx-aarch64_bin-jmods.zip) for aarch64, running `mvn clean package` and then the script https://github.com/gluonhq/scenebuilder/blob/master/.github/scripts/jpackage.sh 

I haven't tested doing it cross platform (from Intel, using the proper JDK, JavaFX, jmods for aarch64), but it might be possible...

Since GitHub doesn't provide runners for M1, you can do it from a self-hosted runner installed on an M1.

**Comment by Siedlerchr** [comment]
Thanks a lot for the insights. Unfortunately my own Macbook is also an Intel one.

**Comment by jperedadnr** [comment]
We'll be adding regular M1 builds to Scene Builder as part of https://github.com/gluonhq/scenebuilder/issues/552, using a self-hosted runner.
