### ISSUE TITLE
Allow ESC key to select parent control in HierarchyTreeView and ContentPane

### ISSUE THREAD

**Issue by luca-domenichini** [gluonhq/scenebuilder#388]
As most of wysiwyg it would be nice to have the ESC key to navigate upwards and select the parent of the selected control on SceneBuilder.

### Expected Behavior
Pressing ESC on ContentPane or on HierarchyTreeView should move the current selection to the parent of the currently selected control.

### Current Behavior
ESC key does nothing.

### Context
I am opening this feature as of point 4 of #236

**Comment by abhinayagarwal** [comment]
My experience with wysiwyg is only limited to Scene Builder. May be @Oliver-Loeffler @jperedadnr will have comments on this.

**Comment by Oliver-Loeffler** [comment]
Well, I've just played with Visual Studio and did not observe that kind of node handling in the tree. But, it is an idea to try out. May be it helps usability. I will play with IntelliJ and Netbeans to figure out, if there is a similar behavior. If so, it would be good when Scene Builder acts in a similar way. Nevertheless, selecting nodes with key strokes is always a good idea. Traversing the scene graph via keyboard can improve productivity.

**Comment by Oliver-Loeffler** [comment]
What I observed in past was, that ESC often cancels any selections.

**Comment by mimmoz81** [comment]
Sorry for being too generic..
I used WindowBuilder for Swing apps on eclipse in the past and when you have many panels nested inside each other and you click on the last leaf node - a button - maybe you wanted to select the parent or the grandparent in order to change to background color for instance..
The point is that sometimes it is difficult in SB to select the parent node because there are too many nested panes and pressing ESC would be a quick shortcut in my opinion.
When the selected node has no parent, pressing ESC will simply unselect the node.

**Comment by Oliver-Loeffler** [comment]
I just found, that in Hierarchy view pressing the left cursor key `<-` collapses the current parent node and also selects the parent if pressed a 2nd time. Having the the cursor to be used in Editor view would be counter intuitive.

I think having `ESC` for direct parent node selection in Editor and Hierarchy is a very good idea. After working a little more with SB during the last months I personally consider this as helpful.

**Comment by pfurbacher** [comment]
Sorry, but I think using ESC in this very non-standard way is a terrible idea. ESC (escape) is universally understood as "get me out of here"! It's never "navigate up the hierarchy" as far as I'm concerned. Perhaps you can cite some odd-ball usage in an app you have used, but in 30+ years of doing interface design, I've never ever considered ESC for anything other than "cancel", as in "let's blow this pop stand". 

Stick with standards: e.g., navigation by key combo in Finder (or Windows Explorer, but it has been so long since I've used it that I can't remember the combination). Command-up-arrow = navigate towards the root (parent). Not surprisingly, Scene Builder actually implements this. So why confuse things and introduce a non-standard key combo?

Also, how is the user going to discover that ESC now has a navigational meaning? There's no way to intuit this meaning. However, knowing that the *standard* key combo is Command-up-arrow, I dropped a textfield on a vbox, selected the textfield and hit Command-up-arrow and voila, the vbox was selected. (SB version 19.0.0)

Don't fix things that ain't broke.

**Comment by Oliver-Loeffler** [comment]
This is an understandable point. How about using the left arrow key for doing this?
As of now `<-` just collapses the selected node if it has children. Pressing `<-` a second time with a node collapsed could then trigger the navigation of one node up. This then would match the behavior observable in MacOS Finder or Windows Explorer.  What do you think?

**Comment by pfurbacher** [comment]
I should probably clarify: when I wrote about command-up-arrow navigation, it was in reference to the Content View (the drawing canvas) in SceneBuilder. Navigation in the Document View is pretty much the same as in Finder (sorry, I can't compare to Windows or Linux because I haven't used them in years).

All in all, I think the current navigation key combos in the respective views are optimal (and standard).

**Comment by Oliver-Loeffler** [comment]
May be instead its better to show the possible navigational key combos as kind of an overlay in the drawing region.

**Comment by Oliver-Loeffler** [comment]
Closed with #389 .
