### ISSUE TITLE
Failed to launch SceneBuilder 17

### ISSUE THREAD

**Issue by pell-je** [gluonhq/scenebuilder#423]
Cannot launch SceneBuilder 17

```

java -jar AppData\Local\SceneBuilder\app\scenebuilder-17.0.0-all.jar

Error: Could not find or load main class com.oracle.javafx.scenebuilder.app.SceneBuilderApp
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Clicking on .exe does nothing so I  tried running .jar directly

**Comment by Oliver-Loeffler** [comment]
Hi @pell-je , 

this is very unfortunate to hear.

SceneBuilder is designed in such way, so that only one instance can run at same time. So if already another version is running, either as standalone or embedded (e.g. in IntelliJ), startup of SB17 will fail. It does not matter which version of SB is running, even a running instance of SB 8.5 or SB11 or SB15 will prevent SB17 from start.

## 1. Can you ensure that no other instance of SB (not even other versions) is running?
Ideally restart or logoff/logon to absolutely ensure that no JVM is there. Then try to start SB alone.

## 2. Would you be so kind and try the following approach to start SB?
What you also could attempt is, to use the bundled runtime to execute SceneBuilder.
This would work as follows on Windows command line:

```cmd
> cd C:\Users\<username>\AppData\Local\SceneBuilder
> runtime\bin\java.exe -Djava.library.path=runtime\bin;runtime\lib -jar app\scenebuilder-17.0.0-all.jar
```

Using the bundled runtime, the error `java.lang.NoClassDefFoundError` should not occur.

Have you checked, if SceneBuilder writes any logfiles?
Those are supposed to be available in `C:\Users\<username>\.scenebuilder\logs`. If there are logfiles, would you be able to provide those?

## 3. If steps 1 and 2 have failed, there could be a locked file which could prevent SB from starting.

SceneBuilder creates a file in `C:\Users\<username>\AppData\Roaming\Scene Builder\MB`.
If this folder and file exists, you could delete the `Scene Builder\MB` directory. After that, restart SB.

## 4 Other options

If all this does not work I am open to make a screen sharing session using "https://meet.jit.si". 
We could test this shorthand there. Its important for me to understand the boundary conditions how and where SB is executed in order to find a possible fix.

In case you're also open for a Jitsi meet, please give me a quick notice so that we can align on a time. I would provide the link. It works very well using any Chromium based browser.

Regards
Oliver

**Comment by Oliver-Loeffler** [comment]
@pell-je Hi, any news on this, have you had the chance to run these tests?

**Comment by pell-je** [comment]
> @pell-je Hi, any news on this, have you had the chance to run these tests?

Hi sorry I did try but I ended up just downgrading in frustration thanks for detailed response.

**Comment by AlmasB** [comment]
Given the latest version is 19, this issue is outdated.
